version: '3'

services:
  postgres:
    image: 'postgres:13.6-alpine'
    container_name: 'grocery'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_DB=my_grocery'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=s3cr3t'